# Generated by Django 4.1.7 on 2023-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingstat',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
