from django.urls import path
from customer import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('dashboard/', views.dashboard, name = "dashboard"),
    path('addRice/', views.addRice, name = "addRice"),
    path('customerHomepage/', views.CustomerHomepage, name = "Customer"),
    path('checkout/', views.Checkout, name = "checkout"),
    path('ricelist/', views.RiceList, name = "ricelist"),
    path('orders/', views.orders, name = "orders"),
    path('update_item/', views.updateItem, name = "update_item"),
    path('process_order/', views.processOrder, name = "process_order"),
    path('CustomerDashboard', views.CustomerDashboard, name = "CustomerDashboard"),
    path('contactUs/', views.Inquiry, name = "contactUs"),
    path('lendingStatus/', views.LendingStatus, name = "lendingStatus"),
    path('customerLendingStatus/', views.CustomerStatus, name = "customerLendingStatus"),
    path('delete/<int:id>', views.deleteRice, name = "deleteRice"),
    path('edit/<int:id>', views.updateRice, name = "updateRice"),
    path('update/<int:id>', views.UpdateOrderStatus, name = "updateOrderStatus"),
    path('updateStat/<int:id>', views.UpdateLendingStatus, name = "updateLendingStatus"),
    path('CustomerInfo/<int:id>', views.CustomerInfo, name = "CustomerInfo"),
    path('OrderDetail/<int:id>', views.OrderDetail, name = "OrderDetail"),
    path('LendingDetail/<int:id>', views.LendingDetail, name = "LendingDetail"),
    path('cancel/<int:id>', views.cancel, name = "cancel"),
    path('NewOrders/', views.NewOrders, name = "NewOrders"),
    path('CancelledOrders/', views.CancelledOrders, name = "CancelledOrders"),
    path('LoanOrders/', views.LoanOrders, name = "LoanOrders"),
    path('NotLoanOrders/', views.NotLoanOrders, name = "NotLoanOrders"),
    # path('export_new_orders/', views.export_new_orders, name = "export_new_orders"),
    path('Date_Desc/', views.Date_Desc, name = "Date_Desc"),
    path('Alphabetical/', views.Alphabetical, name = "Alphabetical"),
    path('Paid/', views.Paid, name = "Paid"),
    path('Unpaid/', views.Unpaid, name = "Unpaid"),
    path('Partially_Paid/', views.Partially_Paid, name = "Partially_Paid"),
    path('Alphabetical_Order/', views.Alphabetical_Order, name = "Alphabetical_Order"),
    path('export_paid/', views.export_paid, name = "export_paid"),
    path('export_unpaid/', views.export_unpaid, name = "export_unpaid"),
    path('export_partially_paid/', views.export_partially_paid, name = "export_partially_paid"),
    path('export_alpha/', views.export_alpha, name = "export_alpha"),
    path('Shipping/', views.Shipping, name = "Shipping"),
    path('Policy/', views.Policies, name = "Policy"),
    path('update_policy/<int:id>', views.Update_Policy, name = "update_policy"),
    path('Update_Shipping/<int:id>', views.Update_Shipping, name = "Update_Shipping"),
    path('search/', views.search, name = "search"),
]